name: Lint PR
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  lint_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.2
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies in the template
        run: (cd template && yarn install)
      - name: Lint the template
        run: (cd template && yarn run lint)
